package routers

import (
	"github.com/xxjwxc/ginrpc"
)

func init() {
	ginrpc.SetVersion(1635219739)
	ginrpc.AddGenOne("Weixin.GetQrcode", "weixin.get_qrcode", []string{"post"})
	ginrpc.AddGenOne("Weixin.Oauth", "weixin.oauth", []string{"post"})
	ginrpc.AddGenOne("Weixin.RefundPay", "weixin.refund_pay", []string{"post"})
	ginrpc.AddGenOne("Weixin.UpdateUserInfo", "weixin.update_user_info", []string{"post"})
	ginrpc.AddGenOne("Upload.UploadMult", "/upload", []string{"post"})
	ginrpc.AddGenOne("Login.Login", "/login/login", []string{"POST"})
	ginrpc.AddGenOne("Login.RefreshToken", "login.refresh_token", []string{"post"})
	ginrpc.AddGenOne("Product.AddAddress", "product.add_address", []string{"post"})
	ginrpc.AddGenOne("Product.AddToBuyTmpCart", "product.add_to_buy_tmp_cart", []string{"post"})
	ginrpc.AddGenOne("Product.AddToCart", "product.add_to_cart", []string{"post"})
	ginrpc.AddGenOne("Product.ChangeCart", "product.change_cart", []string{"post"})
	ginrpc.AddGenOne("Product.Favorite", "product.favorite", []string{"post"})
	ginrpc.AddGenOne("Product.GetAdInfo", "product.get_ad_info", []string{"post"})
	ginrpc.AddGenOne("Product.GetAddress", "product.get_address", []string{"post"})
	ginrpc.AddGenOne("Product.GetAdminAdInfo", "product.get_admin_ad_info", []string{"post"})
	ginrpc.AddGenOne("Product.GetBoutiqueGroup", "product.get_boutique_group", []string{"post"})
	ginrpc.AddGenOne("Product.GetCartList", "product.get_cart_list", []string{"post"})
	ginrpc.AddGenOne("Product.GetFavorite", "product.get_favorite", []string{"post"})
	ginrpc.AddGenOne("Product.GetProductByType", "product.get_product_by_type", []string{"post"})
	ginrpc.AddGenOne("Product.GetProductDetails", "product.get_product_details", []string{"post"})
	ginrpc.AddGenOne("Product.GetProductList", "product.get_product_list", []string{"post"})
	ginrpc.AddGenOne("Product.ReplaceProduct", "product.replace_product", []string{"post"})
	ginrpc.AddGenOne("Product.ReplaceSku", "product.replace_sku", []string{"post"})
	ginrpc.AddGenOne("Product.UpdateSelect", "product.update_select", []string{"post"})
	ginrpc.AddGenOne("Product.UpsetAdminAdInfo", "product.upset_admin_ad_info", []string{"post"})
	ginrpc.AddGenOne("Product.UpsetSkuPrice", "product.upset_sku_price", []string{"post"})
	ginrpc.AddGenOne("Order.AddBillShipment", "order.add_bill_shipment", []string{"post"})
	ginrpc.AddGenOne("Order.CheckPay", "order.check_pay", []string{"post"})
	ginrpc.AddGenOne("Order.DealOrder", "order.deal_order", []string{"post"})
	ginrpc.AddGenOne("Order.DealSystem", "order.deal_system", []string{"post"})
	ginrpc.AddGenOne("Order.GetAfterMsg", "order.get_after_msg", []string{"post"})
	ginrpc.AddGenOne("Order.GetBillInfoByAdmin", "order.get_bill_info_by_admin", []string{"post"})
	ginrpc.AddGenOne("Order.GetMyOrders", "order.get_my_orders", []string{"post"})
	ginrpc.AddGenOne("Order.GetMyOrdersConfig", "order.get_my_orders_config", []string{"post"})
	ginrpc.AddGenOne("Order.GetOrdertrackInfo", "order.get_ordertrack_info", []string{"post"})
	ginrpc.AddGenOne("Order.GetShipmentPost", "order.get_shipment_post", []string{"post"})
	ginrpc.AddGenOne("Order.Pay", "order.pay", []string{"post"})
	ginrpc.AddGenOne("Order.PlaceOrder", "order.place_order", []string{"post"})
	ginrpc.AddGenOne("Order.ReckonFee", "order.reckon_fee", []string{"post"})
	ginrpc.AddGenOne("Coupon.GetAdminCouponInfo", "coupon.get_admin_coupon_info", []string{"post"})
	ginrpc.AddGenOne("Coupon.GetMyCoupon", "coupon.get_my_coupon", []string{"post"})
	ginrpc.AddGenOne("Coupon.GetPromotionCoupon", "coupon.get_promotion_coupon", []string{"post"})
	ginrpc.AddGenOne("Coupon.GoGetCoupon", "coupon.go_get_coupon", []string{"post"})
	ginrpc.AddGenOne("Coupon.UpsetAdminCouponInfo", "coupon.upset_admin_coupon_info", []string{"post"})
	ginrpc.AddGenOne("User.GetUserInfo", "user.get_user_info", []string{"post"})
	ginrpc.AddGenOne("User.LinkUser", "user.link_user", []string{"post"})
	ginrpc.AddGenOne("User.RequestVip", "user.request_vip", []string{"post"})
	ginrpc.AddGenOne("Dist.GetDistList", "dist.get_dist_list", []string{"post"})
	ginrpc.AddGenOne("Dist.RequestDist", "dist.request_dist", []string{"post"})
}
